### ISSUE TITLE
Interfaces vs. concrete implementations

### ISSUE THREAD

**Issue by bitwombat** [Slamdunk/phpstan-laminas-framework#13]
Hi, thanks for taking over this plugin!

I get this PHPStan error:

```
17     Call to an undefined method Laminas\View\Renderer\RendererInterface::partial().
```

And it's because of this code.
```
use Laminas\View\Helper\AbstractHelper;

class UfYouTube extends AbstractHelper
{
    /**
     * Sets the YouTube video identifier
     *
     * @param  string $vid The video identifier
     * @return string A link to the video
     */
    public function __invoke($vid)
    {
        return $this->view->partial('partial/uf-youtube', ['vid' => $vid]);
    }
}
```

So I think the problem for PHPStan is that the view is hinted as `RendererInterface` in `AbstractHelper`, but at runtime is actually a `PhpRenderer`, which has `partial` as a view plugin.

So to fix this am I supposed to extend `AbstractHelper` just to define `$view` as `PhpRenderer`?

Thanks.

**Comment by Slamdunk** [comment]
If you read the README.md you'd see:

> `getView()` method on `\Laminas\View\Helper\AbstractHelper` returns the real `Renderer` instance instead of type-hinted interface

So just use `$this->getView()` method instead of the `view` attribute.

It is always advisable to rely on APIs instead of internals, even for child classes, so I've written this plugin to provide correct return types only for APIs.

**Comment by bitwombat** [comment]
Ah, thanks. I've been looking at this too long. I thought `->view` was handled by a plugin or some other magic.
