### ISSUE TITLE
Allow older php versions - since phpstan does allow it too

### ISSUE THREAD

**Issue by nusphere** [Slamdunk/phpstan-laminas-framework#33]
see #34

**Comment by Slamdunk** [comment]
Hi, thank you for the PR but I do not intend to support PHP < 8.0.

**Comment by nusphere** [comment]
actually php 7.4 is not EOL. And we use PHPStan to upgrade our projects to newer versions.

but there is no possible version to use PHPStan 1.7 with your extension.

@see https://www.php.net/supported-versions.php

**Comment by Slamdunk** [comment]
I know: my spare time is limited, and I chose to support only the versions of PHP that ease my maintenance burden.

This library is MIT licensed though: feel free to fork it and shape it as you need

**Comment by nusphere** [comment]
I can understand very well not to support any versions under php 8.0, but especially with phpstan it makes sense to support at least the current version. With the current setting it is not possible to install a current version of PHPStan. Since version 1.6 of PHPStan, the PSR-11 container has also been broken by BetterReflection, so from now on you will be dependent on your extension.

However, when maintaining a PHP 7.4 project, it is now impossible to use your extension, which is quite sad.

The only solution would be - to develop your own extension, which is not a good solution - since you have already done the work.
