### ISSUE TITLE
PHP 8.2 Support

### ISSUE THREAD

**Issue by internalsystemerror** [Slamdunk/phpstan-laminas-framework#42]
Now released, support for the new minor should be added to this package. I looked into doing this myself and I believe php-cs-fixer is currently holding this up, ~~but I'm not certain why.~~

Edit: Found out why https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues?q=is%3Aissue+is%3Aopen+8.2+label%3Atopic%2FPHP8.2

**Comment by Slamdunk** [comment]
Il bump al my packages next Monday, but any PR is welcome
